### ISSUE TITLE
Documentation, Style and scripting interfaces update

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-math#101]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/issues/101)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------
# Summary

The documentation,  code style, and scripting interfaces in this library needs to be updated. This issue will track progress.

# Work to be done

For each class:

1. Create an example in the `examples` folder. This example should then be used as a doxygen `\snippet` in the class's doxygen description.

2. Check spelling.

3. Check for code style. Set functions should start with `Set`. Don't use `const` with POD types. Etc.

4. Create a scripting interface. See Angle.i as an example.

5. Add more tests so that  coverage is as close to 100% as possible.

6. Target changes to ign-math6. Also, target `main` with any breaking changes.

# Status

1. [x] Angle. See [pull request #325](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/325) and [pull request #326](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/326). https://github.com/ignitionrobotics/ign-math/pull/216
2. [x] AxisAlignedBox https://github.com/ignitionrobotics/ign-math/pull/262 https://github.com/ignitionrobotics/ign-math/pull/261
3. [ ] Box https://github.com/ignitionrobotics/ign-math/pull/273
4. [x] Color https://github.com/ignitionrobotics/ign-math/pull/218
5. [x] Cylinder https://github.com/ignitionrobotics/ign-math/pull/274
6. [ ] DiffDriveOdometry https://github.com/ignitionrobotics/ign-math/pull/265
7. [x] Filter https://github.com/ignitionrobotics/ign-math/pull/230
8. [ ] Frustum https://github.com/ignitionrobotics/ign-math/pull/278
9. [x] GaussMarkovProcess https://github.com/ignitionrobotics/ign-math/pull/216
10. [ ] graph/Edge
11. [ ] graph/GraphAlgorithms
12. [ ] graph/Graph
13. [ ] graph/Vertex
14. [x] Helpers https://github.com/ignitionrobotics/ign-math/pull/266
15. [ ] Inertial https://github.com/ignitionrobotics/ign-math/pull/275
16. [x] Kmeans https://github.com/ignitionrobotics/ign-math/pull/232
17. [x] Line2 https://github.com/ignitionrobotics/ign-math/pull/220
17. [x] Line3 https://github.com/ignitionrobotics/ign-math/pull/220
18. [x] MassMatrix3 https://github.com/ignitionrobotics/ign-math/pull/260
19. [x] Material #234 
20. [x] MaterialType #234
21. [x] Matrix3. See [pull request #328](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/328) https://github.com/ignitionrobotics/ign-math/pull/221
22. [x] Matrix4 https://github.com/ignitionrobotics/ign-math/pull/221
23. [x] MovingWindowFilter https://github.com/ignitionrobotics/ign-math/pull/230
24. [ ] OrientedBox https://github.com/ignitionrobotics/ign-math/pull/276
25. [x] PID https://github.com/ignitionrobotics/ign-math/pull/229
26. [x] Plane https://github.com/ignitionrobotics/ign-math/pull/272
27. [x] Pose3. See [pull request #329](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/329). https://github.com/ignitionrobotics/ign-math/pull/221
28. [x] Quaternion. See [pull request #327](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/327). https://github.com/ignitionrobotics/ign-math/pull/221
29. [x] Rand https://github.com/ignitionrobotics/ign-math/pull/216
30. [x] RollingMean https://github.com/ignitionrobotics/ign-math/pull/218
31. [x] RotationSpline https://github.com/ignitionrobotics/ign-math/pull/230
32. [x] SemanticVersion https://github.com/ignitionrobotics/ign-math/pull/229
33. [x] SignalStats https://github.com/ignitionrobotics/ign-math/pull/220
34. [x] Sphere https://github.com/ignitionrobotics/ign-math/pull/277
35. [x] SphericalCoordiantes https://github.com/ignitionrobotics/ign-math/pull/263
36. [x] Spline https://github.com/ignitionrobotics/ign-math/pull/218
37. [x] Stopwatch https://github.com/ignitionrobotics/ign-math/pull/264
38. [x] Temperature. See [pull request #339](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/339). https://github.com/ignitionrobotics/ign-math/pull/220
39. [x] Triangle3 https://github.com/ignitionrobotics/ign-math/pull/247
40. [x] Triangle https://github.com/ignitionrobotics/ign-math/pull/231
41. [x] Vector2 https://github.com/ignitionrobotics/ign-math/pull/216
42. [x] Vector3 https://github.com/ignitionrobotics/ign-math/pull/216
43. [x] Vector3Stats https://github.com/ignitionrobotics/ign-math/pull/232
44. [x] Vector4 https://github.com/ignitionrobotics/ign-math/pull/216

**Comment by scpeters** [comment]
we should consider providing conversion functions between our ignition math vector and matrix types and numpy arrays.

**Comment by francocipollone** [comment]
- #216 - Sets up SWIG to create bindings to python and create python examples and tests for all the classes that already have a SWIG interface (used for ruby)
 - After the previous is merged, PRs will be adding a swig interface to the remaining classes only for python. (+test)

**Comment by WagnerMarcos** [comment]
At the moment, the python interface we are generating is providing the access to the classes methods using the Cpp name convention (e.g. in python you would use [Temperature.CelsiusToKelvin(temp)](https://github.com/ignitionrobotics/ign-math/blob/474070f8be262beb83b2fbea36872c2147bf52c9/src/Temperature_TEST.py#L56) to invoke the method). This could be modified, seemingly with little effort, using the `%rename(celsius_to_kelvin) CelsiusToKelvin;` SWIG directive in the interface file to get an interface with the PEP8 name convention as used in ROS2. 

Would this be a better approach? Or would it be better to leave it matching the Cpp name convention?

**Comment by francocipollone** [comment]
> At the moment, the python interface we are generating is providing the access to the classes methods using the Cpp name convention (e.g. in python you would use [Temperature.CelsiusToKelvin(temp)](https://github.com/ignitionrobotics/ign-math/blob/474070f8be262beb83b2fbea36872c2147bf52c9/src/Temperature_TEST.py#L56) to invoke the method). This could be modified, seemingly with little effort, using the `%rename(celsius_to_kelvin) CelsiusToKelvin;` SWIG directive in the interface file to get an interface with the PEP8 name convention as used in ROS2.
> 
> Would this be a better approach? Or would it be better to leave it matching the Cpp name convention?

As discussed during the weekly meeting if this isn't much effort we should match ROS2/PEP8 convention.

**Comment by chapulina** [comment]
This issue is mixing a lot of different things. I've broken it into new issues:

> Create an example in the `examples` folder. This example should then be used as a doxygen `\snippet` in the class's doxygen description. 

* https://github.com/ignitionrobotics/ign-math/issues/300

> Check spelling.

* https://github.com/ignitionrobotics/ign-math/issues/303

> Check for code style. Set functions should start with `Set`. Don't use `const` with POD types. Etc. 

* https://github.com/ignitionrobotics/ign-math/issues/301

> Create a scripting interface. See Angle.i as an example.

* https://github.com/ignitionrobotics/ign-math/issues/302

> Add more tests so that  coverage is as close to 100% as possible.

Coverage is already 100%
